version: "3"

services:
  caddy:
    image: clydotron/micro-caddy:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    
  front-end:
    image: clydotron/front-end:1.0.7
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BROKER_URL: "http://backend"
    
  broker-service:
    image: clydotron/broker-service:1.1.3
    deploy:
      mode: replicated
      replicas: 1

  log-service:
    image: clydotron/log-service:1.1.0
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    image: clydotron/auth-service:1.1.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  mongo:
    image: mongo:4.2.17-bionic
    ports:
      - "27017:27017"
    deploy:
      mode: global
    env_file:
      - .env
    volumes:
      - ./db-data/mongo/:/data/db

  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
    
volumes:
  caddy_data:
    external: true
  caddy_config:
    
    
      
      